{% set version = "1.12.0" %}
{% set name = "ldblock" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: d9097bcd8ed27b87d49e01b1e17917c5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: RUnit, BiocGenerics, knitr
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-erma >=0.14.0,<0.16.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfiles >=1.18.0,<1.20.0'
    - 'bioconductor-go.db >=3.7.0,<3.9.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.5.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-snpstats >=1.32.0,<1.34.0'
    - 'bioconductor-variantannotation >=1.28.0,<1.30.0'
    - r-base
    - r-matrix
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-erma >=0.14.0,<0.16.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfiles >=1.18.0,<1.20.0'
    - 'bioconductor-go.db >=3.7.0,<3.9.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.5.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-snpstats >=1.32.0,<1.34.0'
    - 'bioconductor-variantannotation >=1.28.0,<1.30.0'
    - r-base
    - r-matrix
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Define data structures for linkage disequilibrium measures in populations.'

