{% set version = "1.10.0" %}
{% set name = "EGAD" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 798b2f43513b64bec9a70c5a6b387efe
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr, rmarkdown, testthat
requirements:
  host:
    - 'bioconductor-affy >=1.60.0,<1.62.0'
    - 'bioconductor-arrayqualitymetrics >=3.38.0,<3.40.0'
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-geoquery >=2.50.0,<2.52.0'
    - 'bioconductor-impute >=1.56.0,<1.58.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - r-base
    - r-gplots
    - r-igraph
    - r-mass
    - r-matrix
    - r-plyr
    - r-rcolorbrewer
    - r-rcurl
    - r-zoo
  run:
    - 'bioconductor-affy >=1.60.0,<1.62.0'
    - 'bioconductor-arrayqualitymetrics >=3.38.0,<3.40.0'
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-geoquery >=2.50.0,<2.52.0'
    - 'bioconductor-impute >=1.56.0,<1.58.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - r-base
    - r-gplots
    - r-igraph
    - r-mass
    - r-matrix
    - r-plyr
    - r-rcolorbrewer
    - r-rcurl
    - r-zoo
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'The package implements a series of highly efficient tools to calculate functional properties of networks based on guilt by association methods.'

