{% set version = "1.12.0" %}
{% set name = "iCheck" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: e13b3395b8c803eb0f0f12b16ef9c9f8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-affy >=1.60.0,<1.62.0'
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-geneselectmmd >=2.26.0,<2.28.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-lumi >=2.34.0,<2.36.0'
    - 'bioconductor-preprocesscore >=1.44.0,<1.46.0'
    - r-base
    - r-gplots
    - r-lmtest
    - r-mass
    - r-randomforest
    - r-rgl
    - r-scatterplot3d
  run:
    - 'bioconductor-affy >=1.60.0,<1.62.0'
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-geneselectmmd >=2.26.0,<2.28.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-lumi >=2.34.0,<2.36.0'
    - 'bioconductor-preprocesscore >=1.44.0,<1.46.0'
    - r-base
    - r-gplots
    - r-lmtest
    - r-mass
    - r-randomforest
    - r-rgl
    - r-scatterplot3d
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'QC pipeline and data analysis tools for high-dimensional Illumina mRNA expression data.'

