{% set version = "1.2.1" %}
{% set name = "TCGAutils" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: ded15c4190f16c090858878e53fab751
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, curatedTCGAData, devtools, impute, knitr, magrittr, mirbase.db, org.Hs.eg.db, readr, RTCGAToolbox (>= 2.7.5), testthat, TxDb.Hsapiens.UCSC.hg19.knownGene,
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicdatacommons >=1.6.0,<1.8.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-multiassayexperiment >=1.8.0,<1.10.0'
    - 'bioconductor-raggedexperiment >=1.6.0,<1.8.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-rvest
    - r-stringr
    - r-xml2
  run:
    - 'bioconductor-annotationdbi >=1.44.0,<1.46.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicdatacommons >=1.6.0,<1.8.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-multiassayexperiment >=1.8.0,<1.10.0'
    - 'bioconductor-raggedexperiment >=1.6.0,<1.8.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-rvest
    - r-stringr
    - r-xml2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'A suite of helper functions for checking and manipulating TCGA data including data obtained from the curatedTCGAData experiment package. These functions aim to simplify and make working with TCGA data more manageable.'

