{% set version = "1.2.1" %}
{% set name = "MAGeCKFlute" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 80c61e7aae7789fcd50e2f08b97e1d35
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr, rmarkdown, BiocStyle, org.Mm.eg.db
requirements:
  host:
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-clusterprofiler >=3.10.0,<3.12.0'
    - 'bioconductor-dose >=3.8.0,<3.10.0'
    - 'bioconductor-pathview >=1.22.0,<1.24.0'
    - 'bioconductor-sva >=3.30.0,<3.32.0'
    - r-base
    - r-data.table
    - r-ggextra
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-gridextra
    - r-pheatmap
    - r-png
    - r-rcolorbrewer
  run:
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-clusterprofiler >=3.10.0,<3.12.0'
    - 'bioconductor-dose >=3.8.0,<3.10.0'
    - 'bioconductor-pathview >=1.22.0,<1.24.0'
    - 'bioconductor-sva >=3.30.0,<3.32.0'
    - r-base
    - r-data.table
    - r-ggextra
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-gridextra
    - r-pheatmap
    - r-png
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=3)'
  summary: 'MAGeCKFlute is designed to surporting downstream analysis, utilizing the gene summary data provided through MAGeCK or MAGeCK-VISPR. Quality control, normalization, and screen hit identification for CRISPR screen data are performed in pipeline. Identified hits within the pipeline are categorized based on experimental design, and are subsequently interpreted by functional enrichment analysis.'

