{% set version = "1.10.1" %}
{% set name = "iCARE" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 5bd128956683bf6e963fb60e6d62de73
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: RUnit, BiocGenerics
requirements:
  host:
    - r-base
    - r-gtools
    - r-hmisc
    - r-plotrix
  run:
    - r-base
    - r-gtools
    - r-hmisc
    - r-plotrix
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'An R package to compute Individualized Coherent Absolute Risk Estimators.'

