{% set version = "1.38.0" %}
{% set name = "TargetSearch" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: b273595fd72b943d296ea790f67c5fa9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: TargetSearchData, BiocStyle, knitr
requirements:
  host:
    - r-base
    - r-ncdf4
  run:
    - r-base
    - r-ncdf4
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This packages provides a targeted pre-processing method for GC-MS data.'

