{% set version = "1.36.0" %}
{% set name = "DEGseq" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 58f076b21b61831746f37c330442d6c9
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-qvalue >=2.14.0,<2.16.0'
    - r-base
  run:
    - 'bioconductor-qvalue >=2.14.0,<2.16.0'
    - r-base
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>=2)'
  summary: 'DEGseq is an R package to identify differentially expressed genes from RNA-Seq data.'
extra:
  identifiers:
    - biotools:degseq
    - doi:10.1093/bioinformatics/btp612
  parent_recipe:
    name: bioconductor-degseq
    path: recipes/bioconductor-degseq
    version: 1.34.1

