{% set version = "1.6.0" %}
{% set name = "methylInheritance" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 8caf917b45c9ff6f3f2c979b91af0bf1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, BiocGenerics, knitr, rmarkdown, RUnit, methInheritSim
requirements:
  host:
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-methylkit >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-rebus
  run:
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-methylkit >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-rebus
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Permutation analysis, based on Monte Carlo sampling, for testing the hypothesis that the number of conserved differentially methylated elements, between several generations, is associated to an effect inherited from a treatment and that stochastic effect can be dismissed.'

