{% set version = "1.12.0" %}
{% set name = "dupRadar" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: aa807eee2e4f208cc2be7dd2e7bd6715
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, knitr, rmarkdown, AnnotationHub
requirements:
  host:
    - 'bioconductor-rsubread >=1.32.0,<1.34.0'
    - r-base
  run:
    - 'bioconductor-rsubread >=1.32.0,<1.34.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Duplication rate quality control for RNA-Seq datasets.'
extra:
  identifiers:
    - biotools:dupradar
  parent_recipe:
    name: bioconductor-dupradar
    path: recipes/bioconductor-dupradar
    version: 1.10.0

