{% set version = "1.18.0" %}
{% set name = "Rcpi" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 546241e7ceb665ec5d25f589bbd355ca
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr, rmarkdown, RUnit, BiocGenerics
requirements:
  host:
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-chemminer >=3.34.0,<3.36.0'
    - 'bioconductor-fmcsr >=1.24.0,<1.26.0'
    - 'bioconductor-gosemsim >=2.8.0,<2.10.0'
    - r-base
    - r-doparallel
    - r-foreach
    - 'r-rcdk >=3.3.8'
    - r-rcurl
    - r-rjson
  run:
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-chemminer >=3.34.0,<3.36.0'
    - 'bioconductor-fmcsr >=1.24.0,<1.26.0'
    - 'bioconductor-gosemsim >=2.8.0,<2.10.0'
    - r-base
    - r-doparallel
    - r-foreach
    - 'r-rcdk >=3.3.8'
    - r-rcurl
    - r-rjson
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 | file LICENSE'
  summary: 'Rcpi offers a molecular informatics toolkit with a comprehensive integration of bioinformatics and chemoinformatics tools for drug discovery.'

