{% set version = "1.8.3" %}
{% set name = "karyoploteR" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: f0779893b1c8954d4587f922397d4069
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, knitr, testthat, magrittr, BSgenome.Hsapiens.UCSC.hg19, TxDb.Hsapiens.UCSC.hg19.knownGene, pasillaBamSubset
requirements:
  host:
    - 'bioconductor-bamsignals >=1.14.0,<1.16.0'
    - 'bioconductor-biovizbase >=1.30.0,<1.32.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-regioner >=1.14.0,<1.16.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-bezier
    - r-digest
    - r-memoise
  run:
    - 'bioconductor-bamsignals >=1.14.0,<1.16.0'
    - 'bioconductor-biovizbase >=1.30.0,<1.32.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-regioner >=1.14.0,<1.16.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-bezier
    - r-digest
    - r-memoise
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'karyoploteR creates karyotype plots of arbitrary genomes and offers a complete set of functions to plot arbitrary data on them. It mimicks many R base graphics functions coupling them with a coordinate change function automatically mapping the chromosome and data coordinates into the plot coordinates. In addition to the provided data plotting functions, it is easy to add new ones.'

