{% set version = "1.12.0" %}
{% set name = "MEAL" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: fa53c8e7918242e6fadea0f6c9894496
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, IlluminaHumanMethylationEPICanno.ilm10b2.hg19, IlluminaHumanMethylation450kanno.ilmn12.hg19, knitr, minfiData, BiocStyle, rmarkdown, brgedata
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-dmrcate >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gviz >=1.26.0,<1.28.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-minfi >=1.28.0,<1.30.0'
    - 'bioconductor-missmethyl >=1.16.0,<1.18.0'
    - 'bioconductor-multidataset >=1.10.0,<1.12.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - 'r-ggplot2 >=2.0.0'
    - r-isva
    - r-matrixstats
    - r-permute
    - r-smartsva
    - r-vegan
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-dmrcate >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gviz >=1.26.0,<1.28.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-minfi >=1.28.0,<1.30.0'
    - 'bioconductor-missmethyl >=1.16.0,<1.18.0'
    - 'bioconductor-multidataset >=1.10.0,<1.12.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - 'r-ggplot2 >=2.0.0'
    - r-isva
    - r-matrixstats
    - r-permute
    - r-smartsva
    - r-vegan
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Package to integrate methylation and expression data. It can also perform methylation or expression analysis alone. Several plotting functionalities are included as well as a new region analysis based on redundancy analysis. Effect of SNPs on a region can also be estimated.'

