{% set version = "1.2.0" %}
{% set name = "signet" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: a7d5d972d7b4972e3d00625f7fad4bf7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: graphite, BiocStyle, knitr, rmarkdown
requirements:
  host:
    - 'bioconductor-graph >=1.60.0,<1.62.0'
    - 'bioconductor-rbgl >=1.58.0,<1.60.0'
    - r-base
    - r-igraph
  run:
    - 'bioconductor-graph >=1.60.0,<1.62.0'
    - 'bioconductor-rbgl >=1.58.0,<1.60.0'
    - r-base
    - r-igraph
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'An R package to detect selection in biological pathways. Using gene selection scores and biological pathways data, one can search for high-scoring subnetworks of genes within pathways and test their significance.'

