{% set version = "1.6.0" %}
{% set name = "ChIPexoQual" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 611bcc06f4a538ad75e2233cbf3c88ec
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: ChIPexoQualExample (>= 0.99.1), knitr (>= 1.10), BiocStyle, gridExtra (>= 2.2), testthat
requirements:
  host:
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-biovizbase >=1.30.0,<1.32.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - 'r-broom >=0.4'
    - 'r-data.table >=1.9.6'
    - 'r-dplyr >=0.5'
    - 'r-ggplot2 >=1.0'
    - 'r-hexbin >=1.27'
    - 'r-rcolorbrewer >=1.1'
    - r-rmarkdown
    - 'r-scales >=0.4.0'
    - 'r-viridis >=0.3'
  run:
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-biovizbase >=1.30.0,<1.32.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - 'r-broom >=0.4'
    - 'r-data.table >=1.9.6'
    - 'r-dplyr >=0.5'
    - 'r-ggplot2 >=1.0'
    - 'r-hexbin >=1.27'
    - 'r-rcolorbrewer >=1.1'
    - r-rmarkdown
    - 'r-scales >=0.4.0'
    - 'r-viridis >=0.3'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Package with a quality control pipeline for ChIP-exo/nexus data.'

