{% set version = "1.14.0" %}
{% set name = "immunoClust" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: baed4c94cbe3a4c071105ae484d2213d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle
requirements:
  host:
    - 'bioconductor-flowcore >=1.48.0,<1.50.0'
    - r-base
    - r-lattice
  run:
    - 'bioconductor-flowcore >=1.48.0,<1.50.0'
    - r-base
    - r-lattice
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Model based clustering and meta-clustering of Flow Cytometry Data'

