{% set version = "1.0.6" %}
{% set name = "MTseeker" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 32712fee3db29edecc7b398e555850f1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: MTseekerData, BiocStyle, rmarkdown, ggthemes, ggplot2, pkgdown, knitr, rsvg
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gmapr >=1.24.0,<1.26.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.5.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - 'bioconductor-variantannotation >=1.28.0,<1.30.0'
    - 'bioconductor-varianttools >=1.24.0,<1.26.0'
    - r-base
    - r-circlize
    - r-jsonlite
    - r-viridis
    - r-xml2
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.36.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-gmapr >=1.24.0,<1.26.0'
    - 'bioconductor-homo.sapiens >=1.3.0,<1.5.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.44.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - 'bioconductor-variantannotation >=1.28.0,<1.30.0'
    - 'bioconductor-varianttools >=1.24.0,<1.26.0'
    - r-base
    - r-circlize
    - r-jsonlite
    - r-viridis
    - r-xml2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Variant analysis tools for mitochondrial genetics.'

