{% set version = "1.4.0" %}
{% set name = "mpra" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 9cce9441de7898c3c9b32770ace454a4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, knitr, rmarkdown, RUnit
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-scales
    - r-statmod
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-limma >=3.38.0,<3.40.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-scales
    - r-statmod
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Tools for data management, count preprocessing, and differential analysis in massively parallel report assays (MPRA).'

