{% set version = "1.18.0" %}
{% set name = "leeBamViews" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 0ef787cb317db2a29797f2b72a513c60
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: GenomeGraphs, biomaRt, org.Sc.sgd.db, edgeR
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - r-base
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - r-base
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'Artistic 2.0'
  summary: 'data from PMID 19096707; prototype for managing multiple NGS samples'

