{% set version = "2.18.0" %}
{% set name = "easyRNASeq" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: c5f705091d47f5ce587916d1dad93e36
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle (>= 2.7.8), BSgenome (>= 1.39.0), BSgenome.Dmelanogaster.UCSC.dm3 (>= 1.4.0), curl, knitr, rmarkdown, RUnit (>= 0.4.31)
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-deseq >=1.34.0,<1.36.0'
    - 'bioconductor-edger >=3.24.0,<3.26.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomeintervals >=1.38.0,<1.40.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-shortread >=1.40.0,<1.42.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-locfit
    - 'r-lsd >=3.0'
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.18.0'
    - 'bioconductor-biomart >=2.38.0,<2.40.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-deseq >=1.34.0,<1.36.0'
    - 'bioconductor-edger >=3.24.0,<3.26.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomeintervals >=1.38.0,<1.40.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.36.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-shortread >=1.40.0,<1.42.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-locfit
    - 'r-lsd >=3.0'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Calculates the coverage of high-throughput short-reads against a genome of reference and summarizes it per feature of interest (e.g. exon, gene, transcript). The data can be normalized as ''RPKM'' or by the ''DESeq'' or ''edgeR'' package.'
extra:
  identifiers:
    - biotools:easyrnaseq
  parent_recipe:
    name: bioconductor-easyrnaseq
    path: recipes/bioconductor-easyrnaseq
    version: 2.16.0

