{% set version = "1.8.0" %}
{% set name = "MAST" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: bef2e463c8b822c402b8728daba72b3a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr, rmarkdown, testthat, lme4(>= 1.0), roxygen2(> 4.0.0), numDeriv, car, gdata, lattice, GGally, GSEABase, NMF, TxDb.Hsapiens.UCSC.hg19.knownGene, rsvd, limma, RColorBrewer, BiocStyle, scater
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.6.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-abind
    - r-base
    - r-data.table
    - r-ggplot2
    - r-plyr
    - r-progress
    - r-reshape2
    - r-stringr
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.6.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-abind
    - r-base
    - r-data.table
    - r-ggplot2
    - r-plyr
    - r-progress
    - r-reshape2
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL(>= 2)'
  summary: 'Methods and models for handling zero-inflated single cell assay data.'
extra:
  identifiers:
    - biotools:mast
    - doi:10.1186/s13059-015-0844-5
  parent_recipe:
    name: bioconductor-mast
    path: recipes/bioconductor-mast
    version: 1.6.1

