{% set version = "3.7.2" %}
{% set name = "phastCons100way.UCSC.hg19" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 65aa706a567f7e328dbba0095f995cf1
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-genomicscores >=1.6.0,<1.8.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
  run:
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-genomicscores >=1.6.0,<1.8.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Store UCSC phastCons conservation scores for the human genome (hg19) calculated from multiple alignments with other 99 vertebrate species.'
extra:
  parent_recipe:
    name: bioconductor-phastcons100way.ucsc.hg19
    path: recipes/bioconductor-phastcons100way.ucsc.hg19
    version: 3.7.2

