{% set version = "1.0.0" %}
{% set name = "ChemmineDrugs" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: a2d92c1c831cb33db29a838c77ce4f97
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle,knitcitations,knitr
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-chemminer >=3.34.0,<3.36.0'
    - r-base
    - r-rsqlite
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-chemminer >=3.34.0,<3.36.0'
    - r-base
    - r-rsqlite
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'An annotation package for use with ChemmineR. This package includes data from DrugBank and DUD.'

