{% set version = "1.4.0" %}
{% set name = "methInheritSim" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 5f19cadcf31e12a062904345180d8e45
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, knitr, rmarkdown, RUnit, methylInheritance
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-methylkit >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-msm
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.30.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-methylkit >=1.8.0,<1.10.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - r-base
    - r-msm
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Simulate a multigeneration methylation case versus control experiment with inheritance relation using a real control dataset.'

