{% set version = "1.2.0" %}
{% set name = "HDCytoData" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: f5bacd7c970ce24a343b77b8149e7c13
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocStyle, knitr, rmarkdown, FlowSOM, Rtsne, ggplot2
requirements:
  host:
    - 'bioconductor-experimenthub >=1.8.0,<1.10.0'
    - 'bioconductor-flowcore >=1.48.0,<1.50.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
  run:
    - 'bioconductor-experimenthub >=1.8.0,<1.10.0'
    - 'bioconductor-flowcore >=1.48.0,<1.50.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - wget
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Data package containing a set of high-dimensional cytometry data sets saved in SummarizedExperiment and flowSet Bioconductor object formats, including row and column meta-data describing samples, cell populations (clusters), and protein markers.'

