{% set version = "1.2.1" %}
{% set name = "scmeth" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: 3d53d9f2895ad6c888811c939e9b0207
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BSgenome.Mmusculus.UCSC.mm10, BSgenome.Hsapiens.NCBI.GRCh38, TxDb.Hsapiens.UCSC.hg38.knownGene, org.Hs.eg.db, Biobase, BiocGenerics, ggplot2, ggthemes
requirements:
  host:
    - 'bioconductor-annotationhub >=2.14.0,<2.16.0'
    - 'bioconductor-annotatr >=1.8.0,<1.10.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-bsseq >=1.18.0,<1.20.0'
    - 'bioconductor-delayedarray >=0.8.0,<0.10.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-hdf5array >=1.10.0,<1.12.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-dt
    - r-knitr
    - r-reshape2
    - r-rmarkdown
  run:
    - 'bioconductor-annotationhub >=2.14.0,<2.16.0'
    - 'bioconductor-annotatr >=1.8.0,<1.10.0'
    - 'bioconductor-biostrings >=2.50.0,<2.52.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.52.0'
    - 'bioconductor-bsseq >=1.18.0,<1.20.0'
    - 'bioconductor-delayedarray >=0.8.0,<0.10.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-hdf5array >=1.10.0,<1.12.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-dt
    - r-knitr
    - r-reshape2
    - r-rmarkdown
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Functions to analyze methylation data can be found here. Some functions are relevant for single cell methylation data but most other functions can be used for any methylation data. Highlight of this workflow is the comprehensive quality control report.'

