{% set version = "2.28.0" %}
{% set name = "SNPchip" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 6aa3050529ceb3c1500f56d0eb663982
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: crlmm (>= 1.17.14), RUnit
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-oligoclasses >=1.44.0,<1.46.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-foreach
    - r-lattice
  run:
    - 'bioconductor-biobase >=2.42.0,<2.44.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.20.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.36.0'
    - 'bioconductor-iranges >=2.16.0,<2.18.0'
    - 'bioconductor-oligoclasses >=1.44.0,<1.46.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.22.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.14.0'
    - r-base
    - r-foreach
    - r-lattice
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 2)'
  summary: 'Functions for plotting SNP array data; maintained for historical reasons'
extra:
  identifiers:
    - biotools:snpchip
  parent_recipe:
    name: bioconductor-snpchip
    path: recipes/bioconductor-snpchip
    version: 2.26.0

